[tool.poetry]
name = "irt2-llm-prompter"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sglang = {version = "^0.1.14", extras = ["srt"]}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
